services:
  - type: web
    name: hotel-booker-backend
    env: python
    repo: https://github.com/ThisIsAntonio/hotel-booker-fullstack
    branch: main
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: api.settings
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: <tu-clave>
      - key: DEBUG
        value: False

